# my-mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
data:
  index.html: PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJVVEYtOCI+CiAgICA8dGl0bGU+TGVhcm4gRG9ja2VyIGF0IFRlY21pbnQuY29tPC90aXRsZT4KPC9oZWFkPgo8Ym9keT4KICAgIDxoMT5MZWFybiBEb2NrZXIgV2l0aCBVczwvaDE+ICAgCjwvYm9keT4KPC9odG1sPg==