apiVersion: v1
kind: Pod
metadata:
  name: quark-nginx
  # name: syscall-test6
spec:
  runtimeClassName: quark
  containers:
  - name: nginx
    image: nginx
    env:
    - name: APPLICATION_NAME
      value: "nginx"
    - name: SECRET_MANAGER_IP
      value: "10.206.133.76:8000"
    # - name: CMD_ENV_BASED_SECRETS_PATH
    #   value: "quark_mongo/resource/envCmd"
    - name: SHILED_POLICY_PATH
      value: "quark_mongo/resource/policy"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: "200Mi"